# Generated by Django 2.2.4 on 2019-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('entityID', models.CharField(max_length=1024, verbose_name='Identifier der Anwendung')),
                ('sp_displayname', models.CharField(max_length=80)),
                ('consent_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Einwilligung vom')),
                ('revoked_at', models.DateTimeField(auto_now=True, verbose_name='Zurückziehung vom')),
            ],
            options={
                'verbose_name': 'Consent Statement',
                'ordering': ['-created_at'],
                'unique_together': {('userid', 'entityID', 'revoked_at')},
            },
        ),
    ]
