# Generated by Django 2.2.6 on 2019-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50, verbose_name='UserID')),
                ('displayname', models.CharField(default='', max_length=80)),
                ('consentid', models.CharField(max_length=200)),
                ('entityID', models.CharField(max_length=1024, verbose_name='Identifier der Anwendung')),
                ('sp_displayname', models.CharField(max_length=80)),
                ('consent_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Einwilligung vom')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Zurückziehung vom')),
            ],
            options={
                'verbose_name': 'Consent Statement',
                'ordering': ['-created_at'],
                'unique_together': {('consentid', 'entityID', 'revoked_at')},
            },
        ),
    ]
