# Generated by Django 2.2.12 on 2020-04-16 23:30

import consent.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='consentid',
            field=consent.fields.AutocutCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consent',
            name='displayname',
            field=consent.fields.AutocutCharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='consent',
            name='entityID',
            field=consent.fields.AutocutCharField(max_length=1024, verbose_name='Identifier der Anwendung'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='sp_displayname',
            field=consent.fields.AutocutCharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='consent',
            name='uid',
            field=consent.fields.AutocutCharField(default='', max_length=50, verbose_name='UserID'),
        ),
    ]
