# Generated by Django 2.2.4 on 2019-09-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zurückziehung vom'),
        ),
    ]
