# Generated by Django 2.2.4 on 2019-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_auto_20190908_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='displayname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='consent',
            name='uid',
            field=models.CharField(default='', max_length=50, verbose_name='UserID'),
        ),
    ]
